---
title: "Lab 2: Conditional Probability and Bayes' Rule"
subtitle: 'MTH 561: Mathematical Statistics I'
date: "Last updated: `r Sys.Date()`"
output: 
  html_document:
      toc: TRUE
      toc_depth: 2
      toc_float: TRUE
      css: style_MTH561.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

# library(htmltools)
# 
# footer <- div(
#   style = "font-size: 8pt; text-align: right; width: 100%; padding-right: 12pt;", 
#   span(class = "pageNumber"), "/", span(class = "totalPages")
# )
# 
# pagedown::chrome_print(
#   "MTH561_Lab01.html", 
#   options = list(
#     displayHeaderFooter = TRUE, 
#     footerTemplate = format(footer, indent = FALSE),
#     marginTop = 0.4,
#     marginBottom = 0.4
#   )
# )
```



# Section 2.7: Conditional Probability and Independence

1. (2.71) If two events $A$ and $B$ are such that $P(A)=0.5$, $P(B=0.3)$, and $P(A \cap B) =0.1$, find the following:

    a) $P(A \vert B)$
    b) $P(B \vert A)$
    c) $P(A \vert A\cup B)$
    d) $P(A \vert A\cap B)$
    e) $P(A \cap B \vert A\cup B)$

2. (2.72) For a certain population of employees, the percentage passing or failing a job competency exam, listed according to sex, were as shown in the accompanying table. That is, of all the people taking the exam, 24% were in the male-pass category, 16% were in the male-fail category, and so forth. An employee is to be selected randomly from this population. Let $A$ be the event that the employee scores a passing grade on the exam and let $M$ be the event that a male is selected.

    a) Are the events $A$ and $M$ independent?
    b) Are the events $\bar{A}$ and $F$ independent?

Outcome|Male ($M$)|Female ($F$)|Total
-----|-----|-----|-----
Pass ($A$)|24|36|60
Fail ($\bar{A}$)|16|24|40
Total|40|60|100

3. (2.79) If $P(A)>0$, $P(B)>0$, and $P(A) < P(A\vert B)$, show that $P(B)<P(B\vert A)$.

# Section 2.8: The Multiplication Rule and the Additive Law

1. (2.85) If $A$ and $B$ are independent events, show that $A$ and $\bar{B}$ are also independent. Are $\bar{A}$ and $\bar{B}$ independent?

2. (2.87) Suppose that $A$ and $B$ are two events such that $P(A)+P(B)<1$.

    a) What is the smallest possible value for $P(A \cap B)$?
    b) What is the largest possible value for $P(A \cap B)$?
    
3. (2.102) Diseases I and II are prevalent among people in a certain population. It is assumed that 10% of the population will contract disease I sometime during their lifetime, 15% will contract disease II eventually, and 3% will contract both diseases.

    a) Find the probability that a randomly chosen person from this population will contract at least one disease.
    b) Find the conditional probability that a randomly chosen person from this population will contract both diseases, given that he or she has contracted at least one disease.


# Section 2.9: Event Decompositions

1. (Q.2111) An advertising agency notices that approximately 1 in 50 potential buyers of a product sees a given magazine ad, and 1 in 5 sees a corresponding ad on television. One in 100 sees both. One in 3 actually purchases the product after seeing the ad, 1 in 10 without seeing it. What is the probability that a randomly selected potential customer will purchase the product?

2. (Q.2114) A lie detector will show a positive reading (indicate a lie) 10% of the time when a person is telling the truth and 95% of the time when the person is lying. Suppose two people are suspects in a one-person crime and (for certain) one is guilty and will lie. Assume further that the lie detector operates independently for the truthful person and the liar. What is the probability that the detector...

    a) shows a positive reading for both suspects?
    b) shows a positive reading for the guilty suspect and a negative reading for the innocent suspect?
    c) is completely wrong -— that is, that it gives a positive reading for the innocent suspect and a negative reading for the guilty?
    d) gives a positive reading for either or both of the two suspects?

# Section 2.10: Bayes' Rule

1. (Q.125) A diagnostic test for a disease is such that it (correctly) detects the disease in 90% of the individuals who actually have the disease. If a person does not have the disease, the test will report that he/she does not have it with probability 95%. Only 1% of the population has the disease in question. 
    
    a) Find the probability that a randomly selected individual will test positive for the disease.
    b) Assuming someone has tested positive for the disease, find the probability that they actually do have it.
    c) Explain why the probability you found in part 2 is so "extreme".

2. (Q2.129) Males and females are observed to react differently to a given set of circumstances. It has been observed that 70% of the females react positively to these circumstances, whereas only 40% of males react positively. A group of 20 people, 15 female and 5 male, was subjected to these circumstances, and the subjects were asked to describe their reactions on a written questionnaire. A response picked at random from the 20 was negative. What is the probability that it was that of a male?

3. (Q2.135) Of all travelers arriving at a small airport, 60% fly on major airlines, 30% fly on privately owned planes, and the remaining passengers fly on commercially owned planes not belonging to a major airline. Of those traveling on major airlines, 50% are traveling for business reasons, wherease 60% of those on private planes and 90% of those on other commerically owned planes are traveling for business. Suppose we select one passenger at random. What is the probability that this person...

1. Is traveling on business?
2. Is traveling for business on a privately owned plane?
3. Arrived on a privately owned plane, given that the person is traveling for business reasons?



---

# Problems to submit

__Question 1__: Cystic fibrosis (CF) is a hereditary lung disorder that often results in death. It can be inherited only if both parents are carriers of an abnormal gene. In 1989, the CF gene that is abnormal in carriers of cystic fibrosis was identified. The probability that a randomly chosen person carries an abnormal CF gene is 0.03. The CF20m test detects most, but not all harmful mutations of the CF gene. The test is positive for 90% of people who are carriers. It is positive for 1% of people who are not carriers. If you test positive, what is the probability that you are actually a carrier?



__Question 2__: Two events $A$ and $B$ are such that $P(A) = 0.2$, $P(B) =0.3$, and $P(A \cup B) = 0.4$. Find the following:

a) $P(A \cap B)$
b) $P(\bar{A} \cup \bar{B})$
c) $P(A \vert B)$
d) $P(\bar{A} \vert B)$


